Задание 4. Коллекции и потоки
BanderlogCumberbatch/JavaSDET pull request #4
Opened 2024-11-13 11:32 UTC by BanderlogCumberbatch

2024-12-02 08:42 UTC, DS-170 requested changes
Нужно переделать до соответствия условиям задачи

2024-12-02 08:42 UTC, DS-170 commented on .idea/modules.xml
>  <project version="4">
Пакет .idea нужно убрать из ПР и добавить в gitignore (в тот что в корне. Добавить две строчки "/.idea/" и .idea/*) и почистить кэш

2024-12-02 08:42 UTC, DS-170 commented on src/lection_4/Student.java
> +    Double score;
В условии задания сказано что тут должен быть список оценок. Можно Мапу создать {предмет, оценка}, а можно просто список оценок.

2024-12-02 08:42 UTC, DS-170 commented on src/lection_4/Main.java
> +    public static List<Student> passTheSession (List<Student> arr) {
Тут соответственно надо именно среднюю оценку находить из коллекции оценок и удалять из первого списка тех кто не подходит, вместо того чтобы создавать новый список и его выводить.

2024-12-04 11:23 UTC, BanderlogCumberbatch commented
Исправил

________________________________
От: DS-170 ***@***.***>
Отправлено: 2 декабря 2024 г. 11:42
Кому: BanderlogCumberbatch/JavaSDET ***@***.***>
Копия: BanderlogCumberbatch ***@***.***>; Author ***@***.***>
Тема: Re: [BanderlogCumberbatch/JavaSDET] Задание 4. Коллекции и потоки (PR #4)


@DS-170 requested changes on this pull request.

Нужно переделать до соответствия условиям задачи

________________________________

In .idea/modules.xml<https://github.com/BanderlogCumberbatch/JavaSDET/pull/4#discussion_r1865436620>:

> @@ -2,7 +2,7 @@
 <project version="4">


Пакет .idea нужно убрать из ПР и добавить в gitignore (в тот что в корне. Добавить две строчки "/.idea/" и .idea/*) и почистить кэш

________________________________

In src/lection_4/Student.java<https://github.com/BanderlogCumberbatch/JavaSDET/pull/4#discussion_r1865438475>:

> @@ -0,0 +1,21 @@
+package lection_4;
+
+public class Student {
+    String name, group;
+    Integer course;
+    Double score;


В условии задания сказано что тут должен быть список оценок. Можно Мапу создать {предмет, оценка}, а можно просто список оценок.

________________________________

In src/lection_4/Main.java<https://github.com/BanderlogCumberbatch/JavaSDET/pull/4#discussion_r1865441483>:

> +    public static void main(String[] args) {
+        List<Student> students = getStudents();
+
+        List<Student> accepted = passTheSession(students);
+
+        printStudents(students);
+
+        printStudents(accepted);
+
+        printStudents(students, 3);
+
+        printStudents(accepted, 3);
+
+    }
+
+    public static List<Student> passTheSession (List<Student> arr) {


Тут соответственно надо именно среднюю оценку находить из коллекции оценок и удалять из первого списка тех кто не подходит, вместо того чтобы создавать новый список и его выводить.

—
Reply to this email directly, view it on GitHub<https://github.com/BanderlogCumberbatch/JavaSDET/pull/4#pullrequestreview-2472056131>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A77BQVL6SW7DOJOHIORRUSD2DQMQHAVCNFSM6AAAAABRWIPXE2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDINZSGA2TMMJTGE>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2025-01-30 12:45 UTC, merged